metadata.format.version = "1.1"

[versions]

adventure = "4.25.0"
velocity = "3.3.0-SNAPSHOT"
futures = "0.3.5"

configurate = "4.2.0"
assertj = "3.27.6"
miniplaceholders = "3.1.0"
bstats = "3.1.0"
caffeine = "3.2.3"

blossom = "2.2.0"
shadow = "9.3.0"
runvelocity = "3.0.2"

junit = "6.0.1"
mockito = "5.20.0"


[libraries]

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
bstats = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }
configurate = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }
assetrj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
futures = { group = "com.spotify", name = "completable-futures", version.ref = "futures" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
slf4j = "org.slf4j:slf4j-api:2.0.17"
checkerqual = "org.checkerframework:checker-qual:3.52.1"

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.3" }
